### ISSUE TITLE
Doesn't compile with pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux)

### ISSUE THREAD

**Issue by MaidLucy** [janmattfeld/latex-briefvorlage#8]
I just cloned this repository and ran `pdflatex Brief.tex` inside the directory as you would compile any LaTeX document but all I get is an error message for line 11 with a runaway argument of some `}`. (See further information in Brief.log)
[Brief.log](https://github.com/janmattfeld/latex-briefvorlage/files/4852092/Brief.log)

Additonally, this is the output of `pdflatex --version`
```
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.88.0
```

I have no idea what caused this and why it doesn't work anymore. Has been working fine last year when I wrote my last letter with it.

**Comment by janmattfeld** [comment]
I just checked out the repository as is and successfully built with

`pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian)`
`pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian)`
`pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian)`

Did you find out what caused your problem?

**Comment by janmattfeld** [comment]
Closing this for now as not reproducible. Would be great to know what caused your error, though!

**Comment by fabpiaf** [comment]
```
pdfTeX 3.141592653-2.6-1.40.27 (TeX Live 2026/dev/Arch Linux)
kpathsea version 6.4.2/dev
Copyright 2025 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.47; using libpng 1.6.47
Compiled with zlib 1.3.1; using zlib 1.3.1
Compiled with xpdf version 4.04
```
Worked

I had to install though (which is not related to your problem - could perhaps be mentioned in the readme)
```
texlive-fontsextra
texlive-latexextra
texlive-fontsrecommended
```
